---
- name: '[MAIN][OSP] Starting the main'
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "[MAIN][OSP] Starting the OpenStack infrastructure  ...."

# Config a router to connect between the private network and your
# internal physical network. Also, create key pairs to provide access to
# the instances
- name: '[MAIN][OSP] Network configuration and creation of key pairs'
  hosts: jumpbox
  #become: yes
  roles:
    - osp-network
    - osp-keypair

# Create a Custom flavor that defines the compute, memory and storage capacity
# of a Nova node
- name: '[MAIN][OSP] Create m2.small flavor'
  hosts: jumpbox
  tasks:
    - name: Create a m2.small flavor
      os_nova_flavor:
        cloud: ospcloud
        state: present
        name: m2.small
        ram: 2048
        vcpus: 1
        disk: 10
