---
- name: '[MAIN][OSP] Starting the main'
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "[MAIN][OSP] Starting the OpenStack infrastructure  ...."

# Config a router to connect between the private network and your
# internal physical network. Also, create key pairs to provide access to
# the instances
- name: '[MAIN][OSP] Network configuration and creation of key pairs'
  hosts: jumpbox
  #become: yes
  roles:
    - osp-network
    - osp-keypair

# Create a Custom flavor that defines the compute, memory and storage capacity
# of a Nova node
- name: '[MAIN][OSP] Create m2.small flavor'
  hosts: jumpbox
  tasks:
    - name: Create a m2.small flavor
      os_nova_flavor:
        cloud: ospcloud
        state: present
        name: m2.small
        ram: 2048
        vcpus: 1
        disk: 10

- name: '[MAIN][OSP] Create security group and provision the infra for 3tierAPP in OpenStack'
  hosts: jumpbox
  roles:
    - osp-securitygroup
  tasks:
      ##Create Fronend Instance
    - name: Create frontend instance
      include_role:
        name: osp-instances
        vars_from: frontend.yaml
    ###Create App1 server
    - name: Create app1 instance
      include_role:
        name: osp-instances
        vars_from: app1.yaml
    ##Create App2 server
    - name: Create app2 instance
      include_role:
        name: osp-instances
        vars_from: app2.yaml
    ##Create DB server
    - name: Create db instance
      include_role:
        name: osp-instances
        vars_from: db.yaml

- name: '[MAIN] Starting the main'
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "Starting the deploy for the 3Tier APP ...."

- hosts: jumpbox
  gather_facts: true
  roles:
  - name: osp-facts

- name: '[MAIN][FRONTEND] Setup load-balancer tier'
  hosts: frontends
  become: yes
  roles:
    - base-system
    - ha-proxy

- name: '[MAIN][APPDBS] Setup app tier'
  hosts: appdbs
  become: yes
  roles:
    - base-system
    - postgresql

- name: '[MAIN][APPS] Setup app tier'
  hosts: apps
  become: yes
  roles:
    - base-system
    - tomcat
