---
- name: '[INSTALLATION] Install HAProxy'
  yum:
    name: haproxy
    state: latest

- name: '[SERVICE] Enable and start HAProxy'
  service:
    name: haproxy
    state: started
    enabled: yes

- name: '[TEMPLATE] Setup configuration from template'
  template:
    src: haproxy_template.j2
    dest: /etc/haproxy/haproxy.cfg 
    mode: 0644
