---
- name: '[MAIN] Starting the main'
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: ">> Starting the deploy for the 3Tier APP"

- name: '[MAIN][FRONTEND] Setup load-balancer tier'
  hosts: frontends
  become: yes
  roles:
    - {name: base-system, tags: base-system}

- name: '[MAIN][APPS] Setup app tier'
  hosts: appdbs
  become: yes
  roles:
    - {name: base-system}

- name: '[MAIN][APPS] Setup app tier'
  hosts: apps
  become: yes
  roles:
    - {name: base-system}
