---
- name: '[MAIN] Starting the main'
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "Starting the deploy for the 3Tier APP ...."

- name: '[MAIN][FRONTEND] Setup load-balancer tier'
  hosts: frontends
  become: yes
  roles:
    - base-system
    - ha-proxy
- name: '[MAIN][APPDBS] Setup app tier'
  hosts: appdbs
  become: yes
  roles:
    - base-system

- name: '[MAIN][APPS] Setup app tier'
  hosts: apps
  become: yes
  roles:
    - base-system
